"""Stable public vocabulary for the functional simulation core."""

from .codes import (
    ACTION_COUNT,
    DEATH_CAUSE_COUNT,
    RNG_STREAM_COUNT,
    ActionCode,
    DeathCauseCode,
    RngStreamCode,
)
from .dtypes import (
    CODE_DTYPE,
    COUNT_DTYPE,
    ID_DTYPE,
    INDEX_DTYPE,
    MASK_DTYPE,
    REAL_DTYPE,
    STEP_DTYPE,
)
from .ids import (
    FIRST_ID,
    MAX_NEXT_ID,
    NULL_ID,
    IdAllocation,
    IdCounters,
    allocate_agent_ids,
    allocate_genome_ids,
    allocate_ids,
    allocate_lineage_ids,
    create_id_counters,
)
from .rng import (
    PRNG_IMPLEMENTATION,
    RngState,
    advance_rng,
    create_rng_state,
    derive_entity_keys,
    derive_indexed_key,
    derive_stream_key,
)
from .state import PopulationState, SimulationState, WorldState
from .types import AgentId, Array, GenomeId, LineageId, Shape, StepIndex

__all__ = [
    "ACTION_COUNT",
    "CODE_DTYPE",
    "COUNT_DTYPE",
    "DEATH_CAUSE_COUNT",
    "FIRST_ID",
    "ID_DTYPE",
    "INDEX_DTYPE",
    "MASK_DTYPE",
    "MAX_NEXT_ID",
    "NULL_ID",
    "PRNG_IMPLEMENTATION",
    "REAL_DTYPE",
    "RNG_STREAM_COUNT",
    "STEP_DTYPE",
    "ActionCode",
    "AgentId",
    "Array",
    "DeathCauseCode",
    "GenomeId",
    "IdAllocation",
    "IdCounters",
    "LineageId",
    "PopulationState",
    "RngState",
    "RngStreamCode",
    "Shape",
    "SimulationState",
    "StepIndex",
    "WorldState",
    "advance_rng",
    "allocate_agent_ids",
    "allocate_genome_ids",
    "allocate_ids",
    "allocate_lineage_ids",
    "create_id_counters",
    "create_rng_state",
    "derive_entity_keys",
    "derive_indexed_key",
    "derive_stream_key",
]
